@tool
class_name AIRuntimeGenerator
extends RefCounted

const RUNTIME_DIR = "res://_generated_scripts/"
const RUNTIME_SCRIPT_PATH = RUNTIME_DIR + "AIInteractionRuntime.gd"

const RUNTIME_CODE = """
extends Node

## Auto-generated by AI Scene Format Plugin (V2 Architecture).
## Parses the .aiui source, binds vars, and wires interactions at runtime.

var binding_manager: AIBindingManager
var action_dispatcher: AIActionDispatcher

func _ready() -> void:
    var source = get_meta(\"_ai_source\", \"\")
    if source.is_empty(): return
    
    var parser = AIParserBase.new()
    var roots = parser.parse(source)
    
    var vars_ast = null
    var interact_ast = null
    for r in roots:
        if r.type == \"vars\": vars_ast = r
        elif r.type == \"interactivity\": interact_ast = r
        
    binding_manager = AIBindingManager.new()
    binding_manager.vars_changed.connect(_on_vars_changed)
    binding_manager.setup(vars_ast)
    
    action_dispatcher = AIActionDispatcher.new(self, binding_manager)
    
    var interact_parser = AIInteractionParser.new()
    var interactions = interact_parser.parse_interactions(interact_ast)
    _wire_interactions(interactions)

func _on_vars_changed() -> void:
    pass

func _wire_interactions(interactions: Array) -> void:
    for group in interactions:
		var target_path = group.get("target_id", "")
        var target = AIPathResolver.resolve_path(self, target_path)
        if not target: continue
        
		for state in group.get("states", []):
			var s_name = state.get("name", "")
			var s_cond = state.get("condition", "")
			var s_acts = state.get("actions", [])
            
            match s_name:
				"ready":
                    _eval_trigger(s_cond, s_acts, target)
				"hovered":
                    if target is Control:
                        target.mouse_entered.connect(func(): _eval_state(s_cond, s_acts, target, true))
                        target.mouse_exited.connect(func(): _eval_state(s_cond, s_acts, target, false))
				"pressed":
                    if target is BaseButton:
                        target.pressed.connect(func(): _eval_trigger(s_cond, s_acts, target))
                    elif target is Control:
                        target.gui_input.connect(func(event): 
                            if event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT and event.pressed:
                                _eval_trigger(s_cond, s_acts, target)
                        )

func _eval_state(cond: String, acts: Array, target: Node, active: bool) -> void:
    action_dispatcher.binding_manager.evaluated_vars[\"is_hovered\"] = active
    action_dispatcher.binding_manager.evaluated_vars[\"is_pressed\"] = active
    if action_dispatcher.evaluate_condition(cond):
        action_dispatcher.execute_actions(acts, target)

func _eval_trigger(cond: String, acts: Array, target: Node) -> void:
    if action_dispatcher.evaluate_condition(cond):
        action_dispatcher.execute_actions(acts, target)
"""

static func generate_and_attach(root_node: Node, source_text: String) -> void:
	if not root_node: return
	
	root_node.set_meta("_ai_source", source_text)
	
	if not DirAccess.dir_exists_absolute(RUNTIME_DIR):
		DirAccess.make_dir_recursive_absolute(RUNTIME_DIR)
		
	var file = FileAccess.open(RUNTIME_SCRIPT_PATH, FileAccess.WRITE)
	if not file:
		push_error("AI Scene Format: Failed to create runtime script at " + RUNTIME_SCRIPT_PATH)
		return
		
	var safe_code = RUNTIME_CODE.replace("\t", "    ")
	file.store_string(safe_code)
	file.close()
	
	var script = load(RUNTIME_SCRIPT_PATH)
	if script:
		script.reload()
		
	if root_node.get_script() != script:
		root_node.set_script(script)
		
	root_node.notify_property_list_changed()
	EditorInterface.mark_scene_as_unsaved()
